# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0004_auto_20170602_2241'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='exercise',
            field=models.CharField(max_length=100),
        ),
    ]
