# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-12 00:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0005_auto_20170606_2134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercisegroup',
            old_name='name',
            new_name='groupname',
        ),
    ]
